### ISSUE TITLE
可燃冰没有从轨道采集器采集的选项

### ISSUE THREAD

**Issue by HuangFuSL** [DSPCalculator/dsp-calc#2]
如图

![image](https://github.com/DSPCalculator/dsp-calc/assets/56627153/424dbc01-eb8d-4917-b6f9-2dab2a134c68)

**Comment by JimmyZJX** [comment]
我之前也注意到这个问题了，个人建议/计划下次整理代码的时候配方增加注释功能，可以对容易混淆的产出方式添加说明。或者至少对于某些配方（例如挖矿产出的）先备注一下采集机器名称或图标。

**Comment by makuwa8992** [comment]
是我从游戏直接导文件的锅,以前手写的时候是可以的,游戏里可以开采的物品都有个MiningFrom,氢和重氢写着巨星采集但是可燃冰只有可燃冰矿,我给我那配方生成程序加一下特判吧

**Comment by makuwa8992** [comment]
加上了

**Comment by makuwa8992** [comment]
加上了
