### ISSUE TITLE
选了塑料产线后原料中会有氢

### ISSUE THREAD

**Issue by XiaosongWen** [DSPCalculator/dsp-calc#20]
![image](https://github.com/DSPCalculator/dsp-calc/assets/6759395/edc0ae14-cf12-4728-832c-11b6096c1b94)
is this a bug, or expected?

**Comment by makuwa8992** [comment]
氢是你做精炼油时的副产物,这边是告诉你那些东西会导致氢的产出,这里你的氢并不需要轨道采集器去抽取,产能是0 + 120(来自精炼油产线)的意思
