### ISSUE TITLE
产物流向可视化功能

### ISSUE THREAD

**Issue by HuangFuSL** [DSPCalculator/dsp-calc#21]
在[Factoriolab](https://factoriolab.github.io/flow?z=eJwrcKvQMjNQS.JQK6rUMoh3StYyjHcOBBJuJiBWEIgIARJJWoZqxWpllgBE-A0F&v=9)上发现了一个挺好的功能，可以显示每种产物的输入输出流向。感觉这个功能对于水面流用处不大，在设计黑盒的时候或许会有用。

<img width="692" alt="image" src="https://github.com/DSPCalculator/dsp-calc/assets/56627153/6f9f5344-fd97-47e0-b621-0daa7253c0c6">

不过如果产线太复杂的话（比如[白糖](https://factoriolab.github.io/flow?z=eJwrcKrSMjNQS.JQK6rUMoh3StYyjC8FMsy0DNSK1cosAZYcCOI_&v=9)），流向图有也等于没有。

<img width="1362" alt="image" src="https://github.com/DSPCalculator/dsp-calc/assets/56627153/e7412bfb-6fc6-4b9f-b715-2dd7edd5d728">

另外，如果让这个网站来显示[氢油循环生产石墨](https://factoriolab.github.io/flow?z=eJwrKNEyM1BL8lArqtQyiHd2AxJVWobxTslahmrFamWWAJW3CPM_&v=9)的产线会显示一个非常抽象的流向图，这种边界情况可能也要考虑考虑。

<img width="850" alt="image" src="https://github.com/DSPCalculator/dsp-calc/assets/56627153/dadc0da1-93a1-4474-adf0-f94f0c14322e">

或许可以对某个产物专门显示和它相关的生产配方和消耗配方（比如图中的氢）。

<img width="374" alt="image" src="https://github.com/DSPCalculator/dsp-calc/assets/56627153/4b3ce510-999c-4b41-9715-7ab9961ccd14">

**Comment by makuwa8992** [comment]
这个在未来的UI版本里有打算以"溯源"和"追踪"的方式体现,不过不是像Factoriola的这个这样弄成有向图,而是依旧用表格的方式通过按钮手动展现/收起
