### ISSUE TITLE
建议添加电力相关的功能

### ISSUE THREAD

**Issue by HuangFuSL** [DSPCalculator/dsp-calc#3]
功能包括但不限于如下：

1. 达到目标功率所需供电建筑的数量
2. 在目标功率下的燃料消耗速度（燃料消耗的计算可以进一步整合到目前的产量计算器里）

不过生产燃料也要耗电，问题就会变得有点复杂

**Comment by makuwa8992** [comment]
燃料燃烧速度是指什么?如果提供的建筑数量刚好满足电力需求那燃料燃烧速度不是固定的嘛?后期都用小太阳要多少小太阳自己看着耗电量口算一下就行了. 如果是前期的话大多数情况下也是混合电力而不是单一电力, 或者说你期望的是自定义一部分已有电力设施(比如风电等)的情况下自动计算剩余的电力缺口对应的建筑, 同时使用燃料型发电设施的时候也自动把燃料产线归类到总需求的计算里?如果是后者的话问题倒是不太复杂,就是配套UI和现实逻辑之类的工作量有点大, 最近我们正在考虑重构代码, 完成后可以考虑完善这个功能

**Comment by HuangFuSL** [comment]
是的，后期大家都是黑棒黄棒了，也不太需要考虑这个。我当时想的是在前期，主要依靠火电的时候燃料的消耗。比如说要用氢满足电力缺口108MW的供电，需要每分钟至少`108 / 9 / 0.8 * 60 = 900`的产能。不过这个功能确实也没那么重要。

重构这块如果需要帮忙，我也很乐意来。

**Comment by makuwa8992** [comment]
如果愿意来的话可以看看网页链接里的QQ群进群讨论,不过目前重构的框架还没决定,倒是开工以后可能会涉及到一些UI和技术上的问题

**Comment by HuangFuSL** [comment]
好的，我之后看看 这一段刚好比较闲来着
